version: '3.1'

services:
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teste_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=desafionodejs
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data-db:/var/lib/postgresql

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - data-redis:/data

volumes:
  data-redis:
  data-db:
